---

- name: WEB | Install Apache
  yum:
    name: httpd
    state: present

- name: WEB | Ensure apache is running (and enable it at boot)
  service: name=httpd state=started enabled=yes

- name: WEB | Install Php
  yum:
     name:
     - php
     - php-gd
     - php-pear
     state: present

- name: WEB | install Hello World PHP script
  template: src=index.php dest=/var/www/html/index.php mode=0664
  notify:
       - restart apache
