---
- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - vim
    - nano
    - curl

- name: COMMON | Install Apache
  package: name={{ item }} state=present
  with_items:
    - httpd
    - php
    - php-gd 
    - php-pear
