---
# Run with ansible-playbook as following;
# ansible-playbook prepare_newhost_connection.yaml -i newhost -u ubuntu -k --ask-sudo-pass

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)
      
    - name: Copy key to Authorized Key
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# - name: Create ssh dir
#   file: path=/root/.ssh state=directory mode=0700

# - name: Create authorized_keys from our local ssh pubkey
#   lineinfile: dest=/root/.ssh/authorized_keys line="{{ lookup('file', ~/.ssh/id_rsa.pub') }}"
